#!/bin/bash

read -p "Please enter anything here and I can print that for you: " print
myvar=1

while [ $myvar -le 10 ]
do 
	echo $myvar $print
	myvar=$((  $myvar  + 1  ))
	sleep 0.2
done
while [ $myvar -le 10 ]
do 
	echo $myvar $print
	myvar=$((  $myvar  - 1  ))
	sleep 0.2
done
