#!/bin/bash

read -p  "what is the season? " x

if [ "$x" == "winter" ]
then	
	echo "Please, take your coat and scarf"
elif [ "$x" == "spring" ]
then
	echo "Please, take your shirt"
elif [ "$x" == "summer" ]
then 
	echo "Please, take slipper and sunglasses"
elif [ "$x" == "fall" ]
then 
	echo "Please, take your umberella"
fi
